Repository apache/grails-core, pull requests merged in 2024-03, with the labels that each got.

#13413 build: fix github action expression `startsWith`
  .github/workflows/groovy-joint-workflow.yml
Labels: type: build

#13412 Bump spring to version 5.3.33
  gradle.properties
Labels: type: dependency upgrade, relates-to: v5

#13441 fix(build): Increase MaxMetaspaceSize
  gradle.properties
Labels: maintenance, bug, build
