Repository apache/grails-core, pull requests merged in 2024-10, with the labels that each got.

#13711 fix: Register databinders
  grails-plugin-databinding/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: bug

#13714 Fix for sitemesh. Buffering is triggered on response.setContentType so rendering needs to be done on wrapped response.
  grails-web-common/src/main/groovy/org/grails/web/servlet/view/AbstractGrailsView.java
Labels: bug

#13716 build: Remove unused dependency on http-builder
  build.gradle
Labels: maintenance, build

#13717 fix: Compatibility with Groovy 3.0.22
  grails-core/src/main/groovy/grails/beans/util/LazyBeanMap.groovy
Labels: bug

#13719 Pull forward #12494 fix into 6.2.x that was missed in 5.x
  grails-docs/src/main/groovy/grails/doc/gradle/PublishGuide.groovy
Labels: bug

#13721 update profiles to latest releases for Grails 6
  grails-bom/profiles.properties
Labels: maintenance, test

#13723 Add `grails-plugin-events` to `grails-dependencies`
  grails-dependencies/build.gradle
Labels: relates-to: v7

#13737 fix(deps): grails-bom maven group/artifact for micronaut-spring & grails-gradle-plugin
  build.gradle
  grails-bom/build.gradle
Labels: deps, bug

#13755 Fix Bom
  build.gradle
  gradle.properties
  grails-bom/build.gradle
  grails-bom/plugins.properties
Labels: bug

#13740 Fix broken distribution
  build.gradle
  gradle.properties
  gradle/assemble.gradle
  grails-shell/build.gradle
Labels: bug

#13771 remove ancient itext dependency
  gradle.properties
  grails-docs/build.gradle
Labels: maintenance, ci

#13774 Update asciidoctorjVersion
  grails-docs/src/main/groovy/grails/doc/asciidoc/AsciiDocEngine.groovy
Labels: maintenance, ci

#13786 Define Spring Boot dependencies first, then override if needed
  grails-bom/build.gradle
Labels: maintenance, ci

#13806 matrix the build on java 17, 21 and 23 w/ ubuntu, windows and macOS using liberica
  .github/workflows/codeql.yml
  .github/workflows/gradle.yml
  .github/workflows/groovy-joint-workflow.yml
  .github/workflows/release.yml
  .github/workflows/retry-release.yml
  .github/workflows/sdkman.yml
  build.gradle
Labels: maintenance, build

#13809 Filter order values should not be fixed and should be relative to requirements of Spring Boot.
  grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java
  grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy
Labels: bug
