Repository apache/grails-core, pull requests merged in 2024-11, with the labels that each got.

#13817 Allow version resolution for api dependencies
  build.gradle
Labels: maintenance, ci

#13819 Revert "Update to groovy:4.0.24-SNAPSHOT"
  gradle.properties
Labels: revert

#13820 Remove circular transitive gsp dependency
  grails-web-common/build.gradle
  grails-web-databinding/build.gradle
  grails-web-url-mappings/build.gradle
Labels: maintenance, ci

#13838 MultipartHttpServletRequest - Handler mapping introspection fix.
  grails-web-common/src/main/groovy/org/grails/web/servlet/mvc/GrailsWebRequest.java
Labels: bug

#13860 Align versions of transitive dependencies with Grails specified versions
  build.gradle
Labels: maintenance, ci

#13839 update dependencies ahead of Grails 6.2.2
  gradle.properties
  grails-bom/plugins.properties
  grails-bootstrap/src/test/groovy/grails/io/IOUtilsSpec.groovy
Labels: maintenance, ci

#13864 minor grammar fix
  UPGRADE7.md
Labels: bug
