Repository apache/grails-core, pull requests merged in 2024-09, with the labels that each got.

#13622 Update PublishGuide to use Gradle AntBuilder
  grails-docs/src/main/groovy/grails/doc/DocPublisher.groovy
Labels: maintenance, build

#13625 Use groovy.ant.AntBuilder in PublishGuide/DocPublisher
  grails-docs/src/main/groovy/grails/doc/DocPublisher.groovy
Labels: maintenance, build

#13629 Remove installToHomeDist Upload task to fix PublishToMavenLocal
  build.gradle
Labels: bug

#13628 Support controller attribute in tags with resource attribute and resolve correct identity Fixes #13627
  grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultLinkGenerator.groovy
  grails-web-url-mappings/src/test/groovy/org/grails/web/mapping/LinkGeneratorSpec.groovy
Labels: bug

#13652 Revert "Working on #13486"
  grails-plugin-controllers/src/main/groovy/org/grails/compiler/web/ControllerActionTransformer.java
  grails-test-suite-web/src/test/groovy/org/grails/web/commandobjects/CommandObjectsSpec.groovy
Labels: revert

#13658 Use correct hibernate 5 datastore version on test suites
  grails-test-suite-persistence/build.gradle
  grails-test-suite-uber/build.gradle
  grails-test-suite-web/build.gradle
Labels: maintenance, test

#13661 Move all versions numbers to gradle.properties and update dependencies
  build.gradle
  gradle.properties
  gradle/unit-test.gradle
  grails-bootstrap/build.gradle
  grails-codecs/build.gradle
  grails-console/build.gradle
  grails-core/build.gradle
  grails-docs/build.gradle
  grails-docs/src/main/groovy/grails/doc/internal/StringEscapeCategory.java
  grails-encoder/build.gradle
  grails-plugin-datasource/build.gradle
  grails-plugin-services/build.gradle
  grails-plugin-url-mappings/build.gradle
  grails-shell/build.gradle
  grails-spring/build.gradle
  grails-test-suite-persistence/build.gradle
  grails-test-suite-uber/build.gradle
  grails-test-suite-web/build.gradle
  grails-test/build.gradle
  grails-web-common/build.gradle
Labels: maintenance, ci

#13666 fix gdoc task
  gradle/docs.gradle
Labels: bug

#13674 Fix publishGuide task: switch to asciidoctorj version 2.5.13
  gradle.properties
Labels: bug

#13675 fix install task by not combining compileClasspath + runtimeClasspath for grails-shell
  gradle/assemble.gradle
Labels: bug

#13681 ci: Make `groovy-joint-workflow` work as intended
  .github/workflows/groovy-joint-workflow.yml
  build.gradle
Labels: maintenance, bug, build

#13689 Fix tests
  grails-plugin-databinding/build.gradle
  grails-plugin-databinding/src/main/groovy/org/grails/plugins/databinding/DataBindingConfiguration.java
  grails-test-suite-persistence/build.gradle
Labels: maintenance, bug, test

#13691 Temporarily skip tests and publish artifacts
  .github/workflows/gradle.yml
Labels: maintenance, test

#13706 Grails 7 grails-core: update older failing tests
  grails-bootstrap/src/test/groovy/org/grails/build/parsing/CommandLineParserSpec.groovy
  grails-core/src/test/groovy/org/grails/config/PropertySourcesConfigSpec.groovy
  grails-databinding/src/test/groovy/grails/databinding/SimpleDataBinderSpec.groovy
  grails-shell/src/test/groovy/org/grails/cli/profile/repository/MavenRepositorySpec.groovy
  grails-test-suite-uber/src/test/groovy/grails/compiler/GrailsCompileStaticCompilationErrorsSpec.groovy
  grails-web-url-mappings/src/test/groovy/grails/web/mapping/RestfulResourceMappingSpec.groovy
Labels: maintenance, test

#13702 Skip 7.0.x failing tests
  .github/workflows/gradle.yml
  grails-plugin-databinding/src/test/groovy/org/grails/plugins/databinding/DataBindingConfigurationSpec.groovy
  grails-plugin-rest/src/test/groovy/org/grails/plugins/web/rest/render/VndErrorRenderingSpec.groovy
  grails-test-suite-persistence/src/test/groovy/grails/web/databinding/GrailsWebDataBindingListenerSpec.groovy
  grails-test-suite-uber/src/test/groovy/org/grails/plugins/testing/GrailsMockHttpServletRequestTests.groovy
  grails-test-suite-web/src/test/groovy/org/grails/web/mime/ContentFormatControllerTests.groovy
Labels: maintenance, test

#13683 ci: Update and cleanup github workflows
  .github/workflows/gradle.yml
  .github/workflows/groovy-joint-workflow.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/retry-release.yml
  .github/workflows/sdkman.yml
  build.gradle
  gradle.properties
  settings.gradle
Labels: maintenance, ci
