Repository apache/grails-core, pull requests merged in 2024-04, with the labels that each got.

#13450 feat(bom): update versions
  grails-bom/plugins.properties
Labels: feature

#13453 fix(docs): update custom tasks
  grails-docs/src/main/groovy/grails/doc/gradle/PublishGuide.groovy
  grails-docs/src/main/groovy/grails/doc/gradle/PublishPdf.groovy
Labels: bug, documentation

#13452 fix(BOM): update fields plugin coordinates
  build.gradle
  gradle.properties
  grails-bom/plugins.properties
Labels: bug

#13454 fix(grailsdoc): update publish guide task configurations
  grails-docs/src/main/groovy/grails/doc/gradle/PublishGuide.groovy
Labels: bug

#13455 fix(ci): update javaci workflow configurations
  .github/workflows/gradle.yml
Labels: maintenance, ci, bug

#13457 fix(ci): update javaci workflow configurations
  .github/workflows/gradle.yml
Labels: maintenance, ci, bug

#13456 feat(bom): add mongodb bson BOM
  build.gradle
Labels: feature

#13458 fix(grailsdocs): Update PublishGuide task for grails-doc
  grails-docs/src/main/groovy/grails/doc/gradle/PublishGuide.groovy
Labels: bug, documentation

#13459 feat(deps): update gorm hiberante5 to 8.1.0
  gradle.properties
Labels: deps, feature

#13460 fix(deps): update grails views to 3.2.3
  gradle.properties
  grails-bom/plugins.properties
Labels: deps, bug

#13461 Revert "chore(deps): update alpine docker tag to v20240315"
  .github/actions/post-release/Dockerfile
  .github/actions/pre-release/Dockerfile
Labels: maintenance, chore, deps, revert

#13462 revert(ci): Downgrade to Docker alpine 3.16
  .github/actions/post-release/Dockerfile
  .github/actions/pre-release/Dockerfile
Labels: maintenance, ci, revert

#13464 chore(ci): update release workflow configurations
  .github/workflows/release.yml
Labels: maintenance, chore, ci

#13470 chore(bom): Add comment about BOM updates
  build.gradle
Labels: maintenance, chore

#13472 fix(grailsbootstrap): update main-class finder
  grails-bootstrap/src/main/groovy/org/grails/io/support/MainClassFinder.groovy
Labels: bug

#13483 chore: update javadoc comments
  .github/workflows/groovy-joint-workflow.yml
  grails-core/src/main/groovy/grails/util/CacheEntry.java
  grails-core/src/main/groovy/grails/util/GrailsClassUtils.java
  grails-core/src/main/groovy/org/grails/compiler/injection/GrailsASTUtils.java
  grails-core/src/main/groovy/org/grails/spring/context/support/PluginAwareResourceBundleMessageSource.java
  grails-core/src/main/groovy/org/grails/spring/context/support/ReloadableResourceBundleMessageSource.java
  grails-core/src/test/groovy/org/grails/config/PropertySourcesConfigSpec.groovy
  grails-spring/src/main/groovy/grails/spring/BeanBuilder.java
  grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/RegexUrlMapping.java
Labels: maintenance, chore

#13484 chore(build): update build configurations
  build.gradle
  buildSrc/src/main/groovy/org/grails/gradle/FetchGrailsDocSourceTask.groovy
  gradle/assemble.gradle
  gradle/docs.gradle
Labels: maintenance, chore, build

#13488 chore(ci): Update renovate.json
  .github/renovate.json
Labels: maintenance, chore, ci
