Repository apache/grails-core, pull requests merged in 2024-12, with the labels that each got.

#13905 Mark dispatch action as deprecated due to grails-gsp#551
  UPGRADE7.md
  grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingInfo.java
Labels: feature

#13908 Don't set layout if none is specified
  grails-plugin-controllers/src/main/groovy/grails/artefact/controller/support/ResponseRenderer.groovy
  grails-web-common/src/main/groovy/org/grails/web/util/WebUtils.java
Labels: maintenance, ci

#13869 fix #13655 - restore dot notation navigation
  grails-bootstrap/src/main/groovy/org/grails/config/CodeGenConfig.groovy
  grails-bootstrap/src/main/groovy/org/grails/config/NavigableMap.groovy
  grails-bootstrap/src/test/groovy/grails/config/ConfigMapSpec.groovy
  grails-bootstrap/src/test/groovy/grails/config/GrailsConfigSpec.groovy
  grails-core/src/main/groovy/grails/boot/config/GrailsApplicationPostProcessor.groovy
  grails-core/src/main/groovy/org/grails/config/NavigableMapPropertySource.groovy
  grails-core/src/main/groovy/org/grails/plugins/AbstractGrailsPluginManager.java
  grails-core/src/test/groovy/grails/config/PropertySourceConfigSpec.groovy
  grails-core/src/test/groovy/grails/spring/GrailsPlaceholderConfigurerSpec.groovy
  grails-core/src/test/groovy/org/grails/config/NavigableMapPropertySourceSpec.groovy
  grails-core/src/test/groovy/org/grails/config/PropertySourcesConfigSpec.groovy
  grails-core/src/test/groovy/org/grails/config/YamlPropertySourceLoaderSpec.groovy
  grails-core/src/test/groovy/org/grails/transaction/ChainedTransactionManagerPostProcessorSpec.groovy
  grails-plugin-codecs/src/test/groovy/org/grails/web/codecs/HTMLCodecTests.groovy
Labels: bug, feature

#13918 Restore and update GrailsWebDataBindingListenerSpec test
  grails-test-suite-persistence/src/test/groovy/grails/web/databinding/GrailsWebDataBindingListenerSpec.groovy
Labels: maintenance, test

#13926 add link to grails-functional-tests for Java 17-23
  UPGRADE7.md
Labels: maintenance, test

#13935 Add dependencies update versions
  dependabot/build.gradle
  gradle.properties
  grails-bom/build.gradle
  grails-bom/plugins.properties
Labels: maintenance, ci

#13942 Fix purging pre release packages & add missing packages to bom
  .github/workflows/release.yml
  dependabot/build.gradle
  gradle.properties
  grails-bom/build.gradle
Labels: bug

#13946 back to snapshots of dependencies
  gradle.properties
  grails-bom/plugins.properties
  grails-plugin-databinding/build.gradle
  grails-test-suite-persistence/build.gradle
Labels: maintenance, ci

#13947 fix #13945 - use local variable instead of casting the object
  grails-plugin-controllers/src/main/groovy/org/grails/compiler/web/ControllerActionTransformer.java
  grails-test-suite-web/src/test/groovy/org/grails/web/commandobjects/CommandObjectsSpec.groovy
Labels: bug
