Repository apache/grails-core, pull requests merged in 2025-03, with the labels that each got.

#14045 fix(deps): update `asset-pipeline` from 5.0.7 to 5.0.8
  gradle.properties
Labels: deps, bug

#14046 Ensure proper substitution for test projects
  build.gradle
Labels: maintenance, test

#14049 Use environments to prevent accidentally releasing to maven central
  .github/workflows/release.yml
Labels: maintenance, ci

#14048 fix: JavaParser error
  grails-plugin-converters/src/main/groovy/grails/converters/XML.java
Labels: bug

#14062 Update to latest snapshots after M3 release and grails-views consolidation
  gradle.properties
  grails-bom/plugins.properties
  grails-test-suite-uber/src/test/groovy/org/grails/commons/TagLibArtefactHandlerTests.java
  grails-test-suite-uber/src/test/groovy/org/grails/web/servlet/GrailsApplicationAttributesTests.java
Labels: maintenance, test

#14066 Remove @PendingFeature from HomeSpec, now that it passes
  grails-test-examples/app1/src/integration-test/groovy/functionaltests/HomeSpec.groovy
Labels: feature

#14065 Optimize the performance of the Shell CLI by reducing the length of t…
  gradle/assemble.gradle
  grails-shell/build.gradle
Labels: maintenance, ci, perf

#14069 fix #14068 - revert lamba conversion
  grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/UrlMappingsHolderFactoryBean.java
Labels: bug, revert

#14070 remove --refresh-dependencies to avoid Premature end of Content-Length
  .github/workflows/gradle.yml
  .github/workflows/groovy-joint-workflow.yml
Labels: maintenance, ci

#14067 fix: ensure correct application class is used in integration tests
  grails-core/src/main/groovy/org/grails/compiler/injection/ApplicationClassInjector.groovy
  grails-testing-support/src/main/groovy/org/grails/compiler/injection/testing/IntegrationTestMixinTransformation.groovy
Labels: maintenance, bug, test
