Repository apache/grails-core, pull requests merged in 2025-08, with the labels that each got.

#14946 #14930 - make views reproducible by sorting views always
  grails-core/src/main/groovy/org/grails/compiler/injection/GlobalGrailsClassInjectorTransformation.groovy
  grails-gsp/core/src/main/groovy/org/grails/gsp/compiler/GroovyPageCompiler.groovy
Labels: maintenance, chore, ci

#14960 fix: #14947 - class cast exception due to not using local variable
  grails-controllers/src/main/groovy/org/grails/compiler/web/ControllerActionTransformer.java
  grails-test-examples/app1/src/integration-test/groovy/functionaltests/commandobjects/CommandObjectSpec.groovy
Labels: bug

#14950 Issues-14899 fixes Documentation: Cleanup missing files
  grails-data-hibernate5/docs/build.gradle
Labels: bug

#14966 Fix Typo dataStore not dataSource
  grails-doc/src/en/guide/upgrading/upgrading60x.adoc
Labels: bug

#14971 Ensure Gradle Settings file & buildSrc/build.gradle are generated during the build Phase
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/GradleBuildSrcFeature.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/GradleSettingsFileFeature.java
Labels: maintenance, build

#14989 fix: sitemesh3 rendering
  grails-gsp/grails-sitemesh3/src/main/groovy/org/grails/plugins/sitemesh3/Sitemesh3GrailsPlugin.groovy
  grails-gsp/grails-sitemesh3/src/main/groovy/org/grails/plugins/web/taglib/RenderSitemeshTagLib.groovy
  grails-gsp/grails-sitemesh3/src/main/groovy/org/grails/plugins/web/taglib/SitemeshTagLib.groovy
  grails-gsp/spring-boot/src/main/java/grails/gsp/boot/GspAutoConfiguration.java
  grails-test-examples/gsp-sitemesh3/src/integration-test/groovy/EndToEndSpec.groovy
  grails-testing-support-web/src/main/groovy/org/grails/testing/runtime/support/LazyTagLibraryLookup.java
Labels: bug

#15015 Add `.git-blame-ignore-revs`
  .git-blame-ignore-revs
  gradle/rat-root-config.gradle
Labels: maintenance, bug, test

#15019 Forge fixes
  dependencies.gradle
  gradle.properties
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/Category.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/database/TestContainers.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/other/ShadePlugin.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/AssertJ.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/GebWithTestcontainers.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/GebWithWebDriverBinaries.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/GormTestingSupport.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/GrailsWebTestingSupport.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/Hamcrest.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/Mockito.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/TestFeature.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/test/ViewsJsonTestingSupport.java
  grails-forge/grails-forge-core/src/main/resources/pom.xml
  grails-forge/grails-forge-core/src/test/groovy/org/grails/forge/feature/other/ShadePluginSpec.groovy
Labels: bug

#15012 Include sources from composite builds in Groovydoc
  grails-doc/build.gradle
  grails-doc/src/en/guide/plugins/understandingPluginLoadOrder.adoc
  grails-gradle/plugins/README.md
Labels: maintenance, build

#14995 Restart Geb VNC Container for each Test in a Spec to get correct recordings
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/GebRecordingTestListener.groovy
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/GrailsContainerGebExtension.groovy
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/GrailsGebSettings.groovy
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/WebDriverContainerHolder.groovy
  grails-test-examples/geb/build.gradle
  grails-test-examples/geb/src/integration-test/groovy/org/demo/spock/PerTestRecordingSpec.groovy
  grails-test-examples/geb/src/integration-test/groovy/org/demo/spock/pages/HomePage.groovy
Labels: bug

#15033 chore: conform to code style
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/WebDriverContainerHolder.groovy
Labels: maintenance, chore, style

#14987 refactor(grails-geb): Read GebConfig.groovy to allow overriding RemoteWebDriver
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/GrailsGebSettings.groovy
  grails-geb/src/testFixtures/groovy/grails/plugin/geb/WebDriverContainerHolder.groovy
  grails-test-examples/geb-gebconfig/build.gradle
  grails-test-examples/geb-gebconfig/grails-app/assets/images/advancedgrails.svg
  grails-test-examples/geb-gebconfig/grails-app/assets/images/apple-touch-icon-retina.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/apple-touch-icon.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/documentation.svg
  grails-test-examples/geb-gebconfig/grails-app/assets/images/favicon.ico
  grails-test-examples/geb-gebconfig/grails-app/assets/images/grails-cupsonly-logo-white.svg
  grails-test-examples/geb-gebconfig/grails-app/assets/images/grails.svg
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/database_add.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/database_delete.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/database_edit.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/database_save.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/database_table.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/exclamation.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/house.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/information.png
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/sorted_asc.gif
  grails-test-examples/geb-gebconfig/grails-app/assets/images/skin/sorted_desc.gif
  grails-test-examples/geb-gebconfig/grails-app/assets/images/slack.svg
  grails-test-examples/geb-gebconfig/grails-app/assets/images/spinner.gif
  grails-test-examples/geb-gebconfig/grails-app/assets/javascripts/application.js
  grails-test-examples/geb-gebconfig/grails-app/assets/stylesheets/application.css
  grails-test-examples/geb-gebconfig/grails-app/assets/stylesheets/errors.css
  grails-test-examples/geb-gebconfig/grails-app/assets/stylesheets/grails.css
  grails-test-examples/geb-gebconfig/grails-app/assets/stylesheets/main.css
  grails-test-examples/geb-gebconfig/grails-app/assets/stylesheets/mobile.css
  grails-test-examples/geb-gebconfig/grails-app/conf/application.yml
  grails-test-examples/geb-gebconfig/grails-app/conf/logback-spring.xml
  grails-test-examples/geb-gebconfig/grails-app/conf/spring/resources.groovy
  grails-test-examples/geb-gebconfig/grails-app/controllers/org/demo/spock/UrlMappings.groovy
  grails-test-examples/geb-gebconfig/grails-app/i18n/messages.properties
  grails-test-examples/geb-gebconfig/grails-app/init/org/demo/spock/Application.groovy
  grails-test-examples/geb-gebconfig/grails-app/init/org/demo/spock/BootStrap.groovy
  grails-test-examples/geb-gebconfig/grails-app/views/error.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/index.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/layouts/main.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/notFound.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/serverName/index.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/upload/index.gsp
  grails-test-examples/geb-gebconfig/grails-app/views/upload/store.gsp
  grails-test-examples/geb-gebconfig/src/integration-test/groovy/org/demo/spock/GebConfigSpec.groovy
  grails-test-examples/geb-gebconfig/src/integration-test/groovy/org/demo/spock/pages/HomePage.groovy
  grails-test-examples/geb-gebconfig/src/integration-test/resources/GebConfig.groovy
  settings.gradle
Labels: maintenance, refactor

#15031 Explicitly type render(object) to help IntelliJ ambiguous method overloading
  grails-controllers/src/main/groovy/grails/artefact/controller/support/ResponseRenderer.groovy
Labels: maintenance, ci
