Repository apache/grails-core, pull requests merged in 2025-02, with the labels that each got.

#13992 remove graalvm dependencies only required by asset-pipeline gradle plugin
  .sdkmanrc
  dependabot/build.gradle
  gradle.properties
  grails-bom/build.gradle
Labels: maintenance, ci

#14000 set liquibase.version to prevent override from spring-boot-dependencies
  dependabot/build.gradle
  gradle.properties
  grails-bom/build.gradle
Labels: maintenance, ci

#14025 chore: remove obsolete `grails.factories` file
  grails-plugin-services/src/main/resources/META-INF/grails.factories
Labels: maintenance, chore

#14028 fix(deps): update asset-pipeline from 5.0.6 to 5.0.7
  gradle.properties
Labels: deps, bug

#14032 Update test projects to set hibernate-ehcache dependency
  gradle.properties
  grails-test-examples/gorm/build.gradle
  grails-test-examples/hyphenated/build.gradle
Labels: maintenance, test
