Repository apache/grails-core, pull requests merged in 2025-10, with the labels that each got.

#15106 Docs GSP Javascript: Removed deprecated example
  grails-data-hibernate5/dbmigration/README.md
  grails-data-hibernate5/docs/src/docs/asciidoc/databaseMigration/introduction.adoc
  grails-doc/src/en/ref/Tags - GSP/javascript.adoc
Labels: documentation

#15105 15079 - grails-micronaut improvements
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/lang/groovy/application.rocker.raw
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/micronaut/GrailsMicronaut.java
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/micronaut/MicronautHttpClient.java
  grails-forge/grails-forge-core/src/main/resources/pom.xml
  grails-forge/test-core/src/test/groovy/org/grails/forge/create/CreateAppSpec.groovy
Labels: improvement

#15109 First Step in optimizing GSP Performance on Grails 7. Safe small optimizations to start
  grails-gsp/core/src/main/groovy/org/grails/gsp/GroovyPage.java
  grails-gsp/core/src/main/groovy/org/grails/gsp/GroovyPageMetaInfo.java
  grails-gsp/core/src/main/groovy/org/grails/gsp/GroovyPageWritable.java
  grails-gsp/core/src/main/groovy/org/grails/gsp/GroovyPagesTemplateEngine.java
  grails-gsp/core/src/main/groovy/org/grails/gsp/compiler/GroovyPageCompiler.groovy
  grails-gsp/core/src/main/groovy/org/grails/gsp/compiler/GroovyPageParser.java
  grails-gsp/grails-web-gsp/src/main/groovy/org/grails/web/gsp/GroovyPagesTemplateRenderer.java
  grails-gsp/plugin/src/test/groovy/org/grails/gsp/compiler/tags/GroovyEachParseTests.groovy
  grails-gsp/plugin/src/test/groovy/org/grails/web/pages/ParseSpec.groovy
  grails-testing-support-web/src/main/groovy/grails/testing/web/GrailsWebUnitTest.groovy
Labels: maintenance, perf
