Repository apache/grails-core, pull requests merged in 2025-07, with the labels that each got.

#14879 chore: update to 5.0.12 for the asset pipeline
  build.gradle
  buildSrc/build.gradle
  dependencies.gradle
  grails-doc/src/en/guide/upgrading/upgrading60x.adoc
  grails-forge/grails-forge-core/src/main/java/org/grails/forge/build/gradle/GradleRepository.java
  grails-gradle/build.gradle
Labels: maintenance, chore

#14881 Fix spelling
  README.md
  grails-core/src/main/groovy/grails/util/GrailsClassUtils.java
  grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/query/Query.java
  grails-doc/src/en/guide/upgrading/upgrading60x.adoc
  grails-fields/src/main/groovy/org/grails/scaffolding/model/property/DomainProperty.groovy
  grails-test-suite-uber/src/test/groovy/org/grails/commons/GrailsClassUtilsTests.java
  grails-views-gson/src/test/groovy/grails/plugin/json/view/EmbeddedAssociationsSpec.groovy
Labels: bug

#14880 chore: #14779 - add better instructions on how to build & use the source distribution
  CONTRIBUTING.md
  INSTALL
  README.md
Labels: maintenance, chore, build

#14888 fix: #13668 - update for SpringBoot resource split into subclass
  grails-i18n/src/main/groovy/org/grails/plugins/i18n/I18nGrailsPlugin.groovy
Labels: bug

#14893 [skip ci] doc: #14892 - update RELEASE.md for workflow changes and grails-forge repo merge
  RELEASE.md
Labels: maintenance, ci

#14919 fix: #14910 - make property files reproducible by default (per day)
  grails-common/src/main/groovy/org/apache/grails/common/properties/PropertyFileUtils.groovy
  grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy
Labels: maintenance, ci, bug

#14926 fix: #14918 adjust the class loader used for command loading to ensure the delegating cli can find all commands
  grails-core/src/main/groovy/grails/dev/commands/ApplicationContextCommandRegistry.groovy
  grails-shell-cli/src/main/groovy/org/grails/cli/profile/commands/CommandRegistry.groovy
  grails-shell-cli/src/main/groovy/org/grails/cli/profile/commands/factory/ServiceCommandFactory.groovy
  grails-shell-cli/src/main/groovy/org/grails/cli/profile/steps/StepRegistry.groovy
Labels: bug

#14936 Fix issue reported by GitHub CodeQL
  grails-wrapper/src/main/java/grails/init/GrailsUpdater.java
Labels: bug
